### PR TITLE
Runner extra for additional mpi runner options

### PR DESCRIPTION
**Pull request by suchyta1**
This is so the user can give extra command line options to the MPI runner. For example on Theta, to use RDMA, you have to give it the name of your domain in such a way. The changes are not complex. There might be something you want to tweak.

### CODE REVIEW

**Comment by kshitij-v-mehta** [comment]
Do you have a short example of a couple of lines to show how you would use it? I am trying to understand how it is different from https://github.com/CODARcode/cheetah/issues/150

**Comment by kshitij-v-mehta** [comment]
I added a comment to the brusselator example that shows how to use it https://github.com/CODARcode/cheetah/blob/dev/examples/brusselator/cheetah-campaign.py#L74

**Comment by kshitij-v-mehta** [comment]
Eric - does #150 meet your requirements? If so, I will close this PR.

**Comment by suchyta1** [comment]
Yes, go ahead and close it.

On 5/28/19, Kshitij Mehta <notifications@github.com> wrote:
> Eric - does #150 meet your requirements? If so, I will close this PR.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/CODARcode/cheetah/pull/153#issuecomment-496528487


-- 
Eric Suchyta
Oak Ridge National Laboratory
Scientific Data Group
Building 4100, C234
(865) 576-6340
https://suchyta1.github.io/

**Pull request closed without merging**
