### PR TITLE
Fix kill

### LINKED ISSUE #83: Experiments producing no output
All experiments following an experiment that timed out produce no output. No stdout or stderr files are written; the experiments do no seem to run.

@bd4 and @kshitij-v-mehta working on the issue.

### PR DESCRIPTION
**Pull request by bd4**
fixes #83

### CODE REVIEW

**Comment by bd4** [comment]
My theta runs aren't working, and I'm trying to figure out if it's specific to this branch or something else. Would like to hold off on the merge until I get it sorted out, hopefully later this afternoon.

**Comment by kshitij-v-mehta** [comment]
Ok, sounds good.

**Comment by bd4** [comment]
When using cray-python module, I get the following from the aprun calls:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/17.09.1/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/opt/python/17.09.1/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/opt/python/17.09.1/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: /usr/lib/python2.7/lib-dynload/_struct.so: wrong ELF class: ELFCLASS32
XALT_EXCEPTION(xalt_run_submission.py):  No JSON object could be decoded
apsched: request exceeds max nodes, alloc
XALT_EXCEPTION(xalt_run_submission.py):  No JSON object could be decoded
```

When using intelpython35 (currently in submit-env.sh and working on master), I get the same `apsched` error without the python error:
```
apsched: request exceeds max nodes, alloc
```

If I set `start_new_session=False` in Popen, then the aprun launch works, the first runs succeed, but the new logic for detecting completion fails and workflow stalls.

**Comment by bd4** [comment]
I'm unable to resolve this issue on theta. I'm now experimenting different approaches that will work on titan and theta. Will also send email to ALCF support about the issue.

**Pull request merged**
